const express = require("express")
const {verify}  = require("jsonwebtoken")
const router = express.Router()
const {getAllMovies, getMoviesById, addMovies, updateMovies, removeMovies, searchMovies, sortMovies } = require("../controllers/moviesController")
const upload = require("../helper/multer")
const {verifAuth} = require("../helper/verifAuth")

router.get("/", getAllMovies)
router.get("/:id", getMoviesById)
router.post("/", upload.single("image"), addMovies)
router.patch("/:id", verifAuth, upload.single("image"), updateMovies)
router.delete("/:id", verifAuth,removeMovies)
router.post("/search", searchMovies)
router.get("/sort/:sort", sortMovies)
module.exports = router
