const express = require("express")
const {verify}  = require("jsonwebtoken")
const router = express.Router()
const movieController = require("../controllers/moviesController")
const upload = require("../helper/multer")
const {verifAuth} = require("../helper/verifAuth")

router.get("/", movieController.getAllMovies)
router.get("/:id", movieController.getMoviesById)
router.post("/", verifAuth,upload.single("image"), movieController.addMovies)
router.patch("/:id", verifAuth, upload.single("image"), movieController.updateMovies)
router.delete("/:id", verifAuth,movieController.removeMovies)
router.post("/search", movieController.searchMovies)
router.get("/sort/:sort", movieController.sortMovies)
module.exports = router
